modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="applied_thinking"
version="1.0.0"
displayName="Applied_Thinking"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="joshu, MCreator"

[[dependencies.applied_thinking]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




